spring:
  jpa:
    show-sql: false
    generate-ddl: false
    database: MYSQL
  datasource:
    initialize: false
    port: 3306
    platform: mysql
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.dbname}?autoReconnect=true&useUnicode=true&characterEncoding=utf8&noAccessToProcedureBodies=true&protocol=tcp
    driver-class-name: com.mysql.jdbc.Driver
  data.rest:
      returnBodyOnCreate: true
      returnBodyOnupdate: true
keystore:
  path: @keystore.path@
  password: password
  key:
    alias: dev_oauth_jwt_key
    password: password
server:
  port: 8080
  # We need to use a diferent context path to avoid cookie collision in development when don't use different server names
  contextPath: /
logging:
  config: classpath:logback-development.xml
  level:
    com.gpsauriga.sso: DEBUG
    org.springframework.security: DEBUG


---

spring:
  profiles: pro
  datasource:
    host: set host property via env variable
    port: set port property via env variable
    dbname: set dbname property via env variable
    username: set username property via env variable
    password: set password property via env variable
logging.config: classpath:logback-production.xml

---

spring:
  profiles: dev
  jpa:
    show-sql: true
  datasource:
    #esto solo queremos que ocurra en test. Ejecuta schema-${spring.datasource.platform}.sql y data-${spring.datasource.platform}.sql
    initialize: true
    host: localhost
    dbname: oauth_db
    username: oauth_server
    password: password

